// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaT_XBohJG6SiPF5kH_WckNeHG3IjLFQM',
    appId: '1:95851454253:web:c0190df62ac9557053fda4',
    messagingSenderId: '95851454253',
    projectId: 'fir-project-1ed17',
    authDomain: 'fir-project-1ed17.firebaseapp.com',
    storageBucket: 'fir-project-1ed17.firebasestorage.app',
    measurementId: 'G-12VKD6DXBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxaA2m0B3z8Nx_Pp6g6dpvP4AllCCJ7fw',
    appId: '1:95851454253:android:362658e277a4b44853fda4',
    messagingSenderId: '95851454253',
    projectId: 'fir-project-1ed17',
    storageBucket: 'fir-project-1ed17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBwU3oeY0ep5gGwUYdlh00pISjlXr3hU',
    appId: '1:95851454253:ios:ac318e9013c5fa5453fda4',
    messagingSenderId: '95851454253',
    projectId: 'fir-project-1ed17',
    storageBucket: 'fir-project-1ed17.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBwU3oeY0ep5gGwUYdlh00pISjlXr3hU',
    appId: '1:95851454253:ios:ac318e9013c5fa5453fda4',
    messagingSenderId: '95851454253',
    projectId: 'fir-project-1ed17',
    storageBucket: 'fir-project-1ed17.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaT_XBohJG6SiPF5kH_WckNeHG3IjLFQM',
    appId: '1:95851454253:web:af77609487856ba353fda4',
    messagingSenderId: '95851454253',
    projectId: 'fir-project-1ed17',
    authDomain: 'fir-project-1ed17.firebaseapp.com',
    storageBucket: 'fir-project-1ed17.firebasestorage.app',
    measurementId: 'G-78WF730W78',
  );

}