// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8L-VrdxEdpzLVMyQnyBrDlO6WZ37HGg',
    appId: '1:441168981902:web:8b51ad1a25ea4e4464bedf',
    messagingSenderId: '441168981902',
    projectId: 'job-management-ec8f0',
    authDomain: 'job-management-ec8f0.firebaseapp.com',
    storageBucket: 'job-management-ec8f0.firebasestorage.app',
    measurementId: 'G-G7QN9Z9F2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23qJ_tfhZpLIeoYL5dTGBqAz8qJurK50',
    appId: '1:441168981902:android:c0ca4aab7c4d2c0c64bedf',
    messagingSenderId: '441168981902',
    projectId: 'job-management-ec8f0',
    storageBucket: 'job-management-ec8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwogjBwc9De18ay0hX_WlIOEWzaMTBPk',
    appId: '1:441168981902:ios:8dd8e0f23cc8e8fa64bedf',
    messagingSenderId: '441168981902',
    projectId: 'job-management-ec8f0',
    storageBucket: 'job-management-ec8f0.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

}